name:                homelyapp
version:             0.1.0
#synopsis:
#description:
homepage:            https://github.com/matsubara0507/homelyapp#readme
license:             MIT
author:              MATSUBARA Nobutada
maintainer:          nobutada0507@gmail.com
copyright:           2021 MATSUBARA Nobutada
category:            Web
description:         Please see the README on GitHub at <https://github.com/matsubara0507/homelyapp#readme>

extra-source-files:
- README.md
- CHANGELOG.md

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

default-extensions:
- NoImplicitPrelude

- ConstraintKinds
- DataKinds
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiWayIf
- NumericUnderscores
- OverloadedLabels
- OverloadedStrings
- PolyKinds
- RankNTypes
- StandaloneDeriving
- TypeFamilies
- TypeOperators
- TypeSynonymInstances

dependencies:
- base >= 4.7 && < 5
- blaze-html
- rio >= 0.1.1.0
- elmap
- esqueleto
- extensible >= 0.6
- extensible-elmap
- mix
- mix-json-logger
- mix-plugin-persistent-sqlite
- persistent
- persistent-sqlite
- servant-blaze
- servant-elmap
- servant-server
- th-lift-instances
- yaml
- warp

library:
  source-dirs: src

executables:
  homelyapp:
    main: Main.hs
    source-dirs: app/server
    dependencies:
    - homelyapp
    - dotenv

  generate:
    main: Main.hs
    source-dirs: app/generate
    dependencies:
    - homelyapp

tests:
  homelyapp-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - homelyapp
    - tasty
    - tasty-hspec
